# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gic < Formula
  desc "Git-native dotfiles management that doesn't suck"
  homepage "https://github.com/yarlson/gic"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yarlson/gic/releases/download/v0.4.0/gic_Darwin_x86_64.tar.gz"
      sha256 "e0b9f1007ee62c48f9888900f5eec4903f9be14c90fd54fd9d34a8d56d004476"

      def install
        bin.install "gic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yarlson/gic/releases/download/v0.4.0/gic_Darwin_arm64.tar.gz"
      sha256 "fe6963a85697741fcf70732221662ff33e986f09aa49e650fe94576a3242c9a5"

      def install
        bin.install "gic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yarlson/gic/releases/download/v0.4.0/gic_Linux_x86_64.tar.gz"
      sha256 "bba53d5ff29d057a809c951cd71a6d5799c7b7963a32939127e3d90d2f251e46"
      def install
        bin.install "gic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yarlson/gic/releases/download/v0.4.0/gic_Linux_arm64.tar.gz"
      sha256 "50e326bfe13fe73f2bd2bdd228c4ef448b31217bda043e0e5d47ecf66f219832"
      def install
        bin.install "gic"
      end
    end
  end

  test do
    system "#{bin}/gic --version"
  end
end
