# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gic < Formula
  desc "Git-native dotfiles management that doesn't suck"
  homepage "https://github.com/yarlson/gic"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yarlson/gic/releases/download/v0.3.0/gic_Darwin_x86_64.tar.gz"
      sha256 "4d9ba66c15b2302240c6a72bbf8178c8f9d177319a6f011addb61c204c691876"

      def install
        bin.install "gic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yarlson/gic/releases/download/v0.3.0/gic_Darwin_arm64.tar.gz"
      sha256 "39333e2f65427af9d1982a38bce5476a8c00c29623676ee56b9152b6bea4d84f"

      def install
        bin.install "gic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yarlson/gic/releases/download/v0.3.0/gic_Linux_x86_64.tar.gz"
      sha256 "677c79ed63091667da1c1b04e61a4d2cf52717f83907788a554fa2bdb87d3efc"
      def install
        bin.install "gic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yarlson/gic/releases/download/v0.3.0/gic_Linux_arm64.tar.gz"
      sha256 "9d8ca396861e3ecaff47fed4cf249c2d3b92d5a5277331ac7d68b5686b9fd9c4"
      def install
        bin.install "gic"
      end
    end
  end

  test do
    system "#{bin}/gic --version"
  end
end
