# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gic < Formula
  desc "Git-native dotfiles management that doesn't suck"
  homepage "https://github.com/yarlson/gic"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yarlson/gic/releases/download/v0.1.1/gic_Darwin_x86_64.tar.gz"
      sha256 "b62b7059871901bdf9749933d8d0e8307df39d531ecb36dda7265101591b4fbb"

      def install
        bin.install "gic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yarlson/gic/releases/download/v0.1.1/gic_Darwin_arm64.tar.gz"
      sha256 "8341d76505e438bdbd83f9f0ffd5d52d6ff034a99b2b61107e1215f673491acc"

      def install
        bin.install "gic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yarlson/gic/releases/download/v0.1.1/gic_Linux_x86_64.tar.gz"
      sha256 "5afe9daa9933deafb33bfbad56ea55ef453bbce44f6d05b6a89002ab45e7605e"
      def install
        bin.install "gic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yarlson/gic/releases/download/v0.1.1/gic_Linux_arm64.tar.gz"
      sha256 "f538fd79c7319e3c965401ed8725c9f3284b88f37798a401951559a657038518"
      def install
        bin.install "gic"
      end
    end
  end

  test do
    system "#{bin}/gic --version"
  end
end
